version: '2.4'

services:
  app:
    build:
      context: .
      target: prod
    ports:
      - "3030:80"
      - "9229:9229"
    volumes:
      - .:/app
  mongo:
    image: mongo
    volumes:
      - ${PWD}/mongodb/data/db:/data/db
    ports:
      - '27017:27017'
